# Generated by Django 3.0.5 on 2020-10-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=300)),
                ('git', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('EDA', 'EDA'), ('Text Analytics', 'Text Analytics'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Application Developnment', 'Application Developnment')], max_length=75)),
            ],
        ),
    ]
